# Generated by Django 2.1.7 on 2019-03-29 14:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='assignee',
            field=models.ManyToManyField(default='auth.User', to=settings.AUTH_USER_MODEL),
        ),
    ]
