# Generated by Django 2.1.7 on 2019-03-19 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20190318_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='assignee',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
