# Generated by Django 2.1.7 on 2019-03-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20190319_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='assignee_str',
            field=models.TextField(default=1),
        ),
    ]
