# Generated by Django 2.1.7 on 2019-03-20 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_tasks_assignee_str'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='assignee',
            new_name='task_creator',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='assignee_str',
            new_name='task_creator_str',
        ),
    ]
