# Generated by Django 2.1.7 on 2019-03-20 16:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20190320_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='assignees',
            field=models.ManyToManyField(through='tasks.TaskAssignees', to=settings.AUTH_USER_MODEL),
        ),
    ]
